import os
os.system('apt update && apt upgrade -y')
os.system('pkg install python -y')
os.system('pip install requests')
os.system('cd Metainsbul')
os.system('mv MetaSh /data/data/com.termux/files/home')
os.system('chmod +x MetaSh')
os.system('clear')
os.system('cd')
print("Type ./MetaSh to start")
